---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "subvar"
description: Module that separates benign and pathogenic variants from clinvar VCF file.
keywords:
  - variant
  - vcf
  - filtering
  - clinvar
tools:
  - tabix:
      description: Index tab-delimited genome position files
      homepage: http://www.htslib.org/doc/tabix.html
      documentation: http://www.htslib.org/doc/tabix.html
      licence: ["MIT"]
      identifier: biotools:tabix
  - bgzip:
      description: Block compression/decompression utility
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/bgzip.html
      licence: ["MIT"]
  - grep:
      description: Search for patterns in text files
      homepage: https://www.gnu.org/software/grep/
      documentation: https://www.gnu.org/software/grep/manual/
      licence: ["GPL-3.0-or-later"]

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - vcf:
        type: file
        description: Input VCF file containing variants
        pattern: "*.{vcf,vcf.gz}"
  - bed:
      type: file
      description: BED file containing regions of interest
      pattern: "*.bed"

output:
  - benign_vcf:
      - meta:
          type: map
          description: Groovy Map containing sample information
      - "*_benign.vcf":
          type: file
          description: VCF file containing benign variants
          pattern: "*_benign.vcf"
  - pathogenic_vcf:
      - meta:
          type: map
          description: Groovy Map containing sample information
      - "*_pathogenic.vcf":
          type: file
          description: VCF file containing pathogenic variants
          pattern: "*_pathogenic.vcf"
  - selected_vcf:
      - meta:
          type: map
          description: Groovy Map containing sample information
      - "*_ontarget.vcf.gz":
          type: file
          description: VCF file containing variants in target regions
          pattern: "*_ontarget.vcf.gz"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@DavideBag"
maintainers:
  - "@DavideBag"
