---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "pyconvertosim"
description: Converts VCF files to variation files for simulation
keywords:
  - vcf
  - variation
  - simulation
  - conversion
tools:
  - python:
      description: Python programming language
      homepage: https://www.python.org/
      documentation: https://docs.python.org/
      licence: ["PSF-2.0"]
      version: "3.9.21"
  - sort:
      description: Sort lines in text files
      homepage: https://www.gnu.org/software/coreutils/
      documentation: https://www.gnu.org/software/coreutils/manual/
      licence: ["GPL-3.0-or-later"]
  - awk:
      description: Pattern scanning and processing language
      homepage: https://www.gnu.org/software/gawk/
      documentation: https://www.gnu.org/software/gawk/manual/
      licence: ["GPL-3.0-or-later"]
input:
  - - meta:
        type: map
        description: Metadata map for benign VCF
    - vcf_benign:
        type: file
        description: Input VCF file with benign variants
        pattern: "*.vcf"
  - - meta2:
        type: map
        description: Metadata map for pathogenic VCF
    - vcf_pathogenic:
        type: file
        description: Input VCF file with pathogenic variants
        pattern: "*.vcf"
output:
  - base_variation:
      - meta:
          type: map
          description: Metadata map
      - "*_base_variation.txt":
          type: file
          description: Output file containing base variations
          pattern: "*_base_variation.txt"
  - patho_variation:
      - meta:
          type: map
          description: Metadata map
      - "*_patho_variation.txt":
          type: file
          description: Output file containing pathogenic variations
          pattern: "*_patho_variation.txt"
  - combined_variations:
      - meta:
          type: map
          description: Metadata map
      - "*_simvar_*_*.txt":
          type: file
          description: Output files containing combined variations
          pattern: "*_simvar_*_*.txt"
  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@DavideBag"
maintainers:
  - "@DavideBag"
