---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "pyconvertosim"
## TODO nf-core: Add a description of the module and list keywords
description: Converts VCF files to variation files for simulation
keywords:
  - vcf
  - variation
  - simulation
  - conversion
tools:
  - python:
      description: Python programming language
      homepage: https://www.python.org/
      documentation: https://docs.python.org/
input:
  - - meta:
        type: map
        description: Metadata map
    - vcf_benign:
        type: file
        description: Input VCF file with benign variants
        pattern: "*.vcf"
    - vcf_pathogenic:
        type: file
        description: Input VCF file with pathogenic variants
        pattern: "*.vcf"
output:
  - profile:
    - meta:
        type: map
        description: Metadata map
    - base_variation:
        type: file
        description: Output file containing base variations
        pattern: "*_base_variation.txt"
    - patho_variation:
        type: file
        description: Output file containing pathogenic variations
        pattern: "*_patho_variation.txt"
    - combined_variations:
        type: file
        description: Output files containing combined variations
        pattern: "*_variation_*.txt"
  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@DavideBag"
maintainers:
  - "@DavideBag"
