---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bioconductor-deseq2=1.46.0
  - bioconda::bioconductor-tximport=1.34.0
  - conda-forge::r-tidyverse=2.0.0
  - conda-forge::r-pheatmap=1.0.12
