name: "deanalysis"
description: runs a differential expression analysis with DESeq2
keywords:
  - differential
  - expression
  - rna-seq
  - deseq2
tools:
  - deseq2:
      description: "Differential gene expression analysis based on the negative binomial distribution"
      homepage: "https://bioconductor.org/packages/release/bioc/html/DESeq2.html"
      documentation: "https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html"
      tool_dev_url: "https://github.com/mikelove/DESeq2"
      doi: "10.1186/s13059-014-0550-8"
      licence: ["LGPL >=3"]
      identifier: "biotools:deseq2"
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id: 'simulation_id', chromosome: 'chr_number', genes: 'A, B, C', reps: 3, groups: 2 ]`
    - quant:
        type: path
        description: Path to the Salmon quantification files
        pattern: "quant.sf"
  - - transcriptData:
        type: file
        description: Tibble containing transcript data emitted by the subsetgff module
        pattern: "transcriptData.rds"
output:
  - results:
      - meta:
          type: file
          description: TSV-format table of DE genes
          pattern: "deseq2_results.tsv"
      - "deseq2_results.tsv":
          type: file
          description: TSV-format table of DE genes
          pattern: "deseq2_results.tsv"
  - deseq2_ma_plot:
      - meta:
          type: file
          description: MA plot generated by DESeq2
          pattern: "deseq2_ma_plot.pdf"
      - "deseq2_ma_plot.pdf":
          type: file
          description: MA plot generated by DESeq2
          pattern: "deseq2_ma_plot.pdf"
  - deseq2_dispersion_plot:
      - meta:
          type: file
          description: Dispersion plot generated by DESeq2
          pattern: "deseq2_dispersion_plot.pdf"
      - "deseq2_dispersion_plot.pdf":
          type: file
          description: Dispersion plot generated by DESeq2
          pattern: "deseq2_dispersion_plot.pdf"
  - deseq2_count_plot:
      - meta:
          type: file
          description: Plot of normalised counts
          pattern: "deseq2_count_plot.pdf"
      - "deseq2_count_plot.pdf":
          type: file
          description: Plot of normalised counts
          pattern: "deseq2_count_plot.pdf"
  - deseq2_heatmap_plot:
      - meta:
          type: file
          description: Heatmap of top 20 expressed genes
          pattern: "deseq2_heatmap_plot.pdf"
      - "deseq2_heatmap_plot.pdf":
          type: file
          description: Heatmap of top 20 expressed genes
          pattern: "deseq2_heatmap_plot.pdf"
  - deseq2_pca_plot:
      - meta:
          type: file
          description: PCA plot
          pattern: "deseq2_pca_plot.pdf"
      - "deseq2_pca_plot.pdf":
          type: file
          description: PCA plot
          pattern: "deseq2_pca_plot.pdf"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@LorenzoS96"
maintainers:
  - "@LorenzoS96"
