name: "deanalysis"
description: runs a differential expression analysis with DESeq2
keywords:
  - differential
  - expression
  - rna-seq
  - deseq2
tools:
  - deseq2:
      description: "Differential gene expression analysis based on the negative binomial distribution"
      homepage: "https://bioconductor.org/packages/release/bioc/html/DESeq2.html"
      documentation: "https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html"
      tool_dev_url: "https://github.com/mikelove/DESeq2"
      doi: "10.1186/s13059-014-0550-8"
      licence: ["LGPL >=3"]
      identifier: "biotools:deseq2"
  - tximport:
      description: "Import and summarize transcript-level estimates for gene-level analysis"
      homepage: "https://bioconductor.org/packages/release/bioc/html/tximport.html"
      documentation: "https://bioconductor.org/packages/release/bioc/vignettes/tximport/inst/doc/tximport.html"
      tool_dev_url: "https://github.com/mikelove/tximport"
      doi: "10.12688/f1000research.7563.2 "
      licence: ["GPL-3"]
      identifier: "biotools-tximport"
  - tidyverse:
      description: "A collection of R packages designed for data science"
      homepage: "https://www.tidyverse.org/"
      documentation: "https://www.tidyverse.org/packages/"
      tool_dev_url: "https://github.com/tidyverse"
      doi: "10.21105/joss.01686"
      licence: ["MIT"]
      identifier: "r-tidyverse"
  - pheatmap:
      description: "A package to generate heatmaps for data visualization"
      homepage: "https://cran.r-project.org/package=pheatmap"
      documentation: "https://cran.r-project.org/web/packages/pheatmap/pheatmap.pdf"
      tool_dev_url: "https://github.com/raivokolde/pheatmap"
      doi: "10.32614/CRAN.package.pheatmap"
      licence: ["GPL-2"]
      identifier: "biotools:pheatmap"
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id: 'simulation_id', chromosome: 'chr_number', genes: 'A,B,C', reps: 3, groups: 2 ]`
    - quant:
        type: path
        description: Path to the Salmon quantification files
        pattern: "quant.sf"
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id: 'simulation_id', chromosome: 'chr_number', genes: 'A,B,C', reps: 3, groups: 2 ]`
    - quant:
        type: path
        description: Path to the Salmon quantification files
        pattern: "quant.sf"
  - - transcriptData:
        type: file
        description: RDS containing transcript data emitted by the subsetgff module
        pattern: "*.rds"
output:
  - results:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id: 'simulation_id', chromosome: 'chr_number', genes: 'A,B,C', reps: 3, groups: 2 ]`
      - "deseq2_results.tsv":
          type: file
          description: TSV containing the DESeq2 results
          pattern: "deseq2_results.tsv"
      - "deseq2_tx2gene.tsv":
          type: file
          description: TSV containing the association between genes_id and transcripts_id
          pattern: "deseq2_results.tsv"
      - "deseq2_de_genes.txt":
          type: file
          description: file containing the DE genes (padj < 0.05)
          pattern: "deseq2_de_genes.txt"
      - "deseq2_ma_plot.pdf":
          type: file
          description: MA plot generated by DESeq2
          pattern: "deseq2_ma_plot.pdf"
      - "deseq2_dispersion_plot.pdf":
          type: file
          description: Dispersion plot generated by DESeq2
          pattern: "deseq2_dispersion_plot.pdf"
      - "deseq2_count_plot.pdf":
          type: file
          description: Plot of normalised counts
          pattern: "deseq2_count_plot.pdf"
      - "deseq2_heatmap_plot.pdf":
          type: file
          description: Heatmap of top 20 expressed genes
          pattern: "deseq2_heatmap_plot.pdf"
      - "deseq2_pca_plot.pdf":
          type: file
          description: PCA plot
          pattern: "deseq2_pca_plot.pdf"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@LorenzoS96"
maintainers:
  - "@LorenzoS96"
