---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "simuscop_seqtoprofile"
description: Create sequencing profiles to be used for reads simulation
keywords:
  - simulate
  - sequencing
  - genomics
tools:
  - "simuscop":
      description: "Tool to Simulate Illumina Sequencing data based on position and Context dependent Profiles with the ability to inject specific variants into the simulated reads"
      homepage: "https://github.com/qasimyu/simuscop"
      documentation: "https://github.com/qasimyu/simuscop/blob/master/docs/SimuSCoP_User_Guide.pdf"
      tool_dev_url: "https://github.com/qasimyu/simuscop"
      doi: "no DOI available"
      licence: ["GNU GPL v3"]
      identifier: biotools:simuscop

input:
  # Only when we have meta
  - - meta:
        type: map
        description: |
          Groovy Map containing simulation information
          e.g. `[ id:'simulation_id', reps:3, groups:2 ]`
    - bam:
        type: file
        description: Recalibrated BAM file
        pattern: "*.bam"
  - - meta:
        type: map
        description: |
          Groovy Map containing simulation information
          e.g. `[ id:'simulation_id', reps:3, groups:2 ]`
    - vcf:
        type: file
        description: Normal variants VCF file (uncompressed)
        pattern: "*.vcf"
  - - capture:
        type: file
        description: Padded 500bp capture needed to make sure reads are correctly simulated to overlap the actual capture
        pattern: "*.bed"
  - - fasta:
        type: file
        description: FASTA reference file, containing only the chromosome selected for simulation
        pattern: "*.fasta"

output:
  - profile:
    - meta:
        type: map
        description: |
          Groovy Map containing simulation information
          e.g. `[ id:'simulation_id', reps:3, groups:2 ]`
    - "*.profile":
        type: file
        description: Sequencing simulation profile
        pattern: "*.profile"

  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@lescai"
maintainers:
  - "@lescai"
