---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::bash=5.2.21
  - conda-forge::grep=3.11
  - conda-forge::gzip=1.13
