---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "dnavalidation"
description: This module validates DNA sequences by checking if a simulated variant is present in the VCF file and copies the relevant files to a validation directory.
keywords:
  - dna
  - validation
  - vcf
  - fastq
tools:
  - "dnavalidation":
      description: "This module validates DNA sequences by checking if a simulated variant is present in the VCF file and copies the relevant files to a validation directory."
      homepage: "https://github.com/lescai-teaching/eduomics"
      documentation: "https://github.com/lescai-teaching/eduomics"
      tool_dev_url: "https://github.com/lescai-teaching/eduomics"

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', simulatedvar:'chr22-18078561-G-A' ]`
    - vcf:
        type: file
        description: VCF file containing variant information
        pattern: "*.vcf"
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information for reads
          e.g. [ id:'sample1', simulatedvar:'chr22-18078561-G-A' ]
    - reads:
        type: file
        description: FASTQ files containing sequencing reads
        pattern: "*.fastq.gz"

output:
  - dna_validated_results:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', simulatedvar:'chr22-18078561-G-A' ]`
      - "dna_*_validation":
          type: directory
          description: Directory containing validated DNA files
          pattern: "dna_*_validation"
  - vcf_file:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', simulatedvar:'chr22-18078561-G-A' ]`
      - "dna_*_validation/*.vcf":
          type: file
          description: Validated VCF file
          pattern: "dna_*_validation/*.vcf"
  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@DavideBag"
maintainers:
  - "@DavideBag"
