# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "simulate_rnaseq_reads"
description: Simulates RNA-seq reads based on count matrices and fold changes
keywords:
  - RNA-seq
  - simulation
  - count matrices
  - polyester
components:
  - countmatrices
  - polyester_simulate
input:
  - ch_filtered_txfasta:
      description: |
        Channel with the filtered transcript fasta file
        Structure: [ val(meta), path(filtered_txfasta) ]
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'test', chromosome: 'chr22', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3 ]`
        - filtered_txfasta:
            type: file
            description: transcriptome FASTA file containing transcripts from the simulated chromosome
            pattern: "gencode_transcripts_noversion.fasta"
  - ch_filtered_transcriptData:
      description: |
        Channel containing the filtered transcript data from the simulated chromosome
        Structure: [ val(meta), path(filtered_transcriptData) ]
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'test', chromosome: 'chr22', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3 ]`
        - filtered_transcriptData:
            type: file
            description: RDS file containing filtered transcript data from the simulated chromosome
            pattern: "filtered_transcriptData.rds"
  - ch_genelists:
      description: |
        Channel containing those gene lists that should give an enrichment with EnrichGO
        Structure: [ val(meta), path(genelists) ]
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'test', chromosome: 'chr22', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3 ]`
        - genelists:
            type: file
            description: RDS file containing those gene lists that should give an enrichment with EnrichGO
            pattern: "valid_gene_lists.rds"
  - ch_foldchange:
      description: |
        Channel containing fold changes
        Structure: [ val(meta), path(foldchange) ]
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'test', chromosome: 'chr22', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3 ]`
        - foldchange:
            type: file
            description: fold change files
            pattern: "*.rds"
  - ch_gene_list_association:
      description: |
        Channel containing the association between a specific list and its genes
        Structure: [ val(meta), path(gene_list_association) ]
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'test', chromosome: 'chr22', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3 ]`
        - gene_list_association:
            type: file
            description: TSV file containing the association between a specific list and its genes
            pattern: "list_gene_association.tsv"
output:
  - countMatrix:
      description: |
        Channel containing the count matrices associated to each gene list
        Structure: [ val(meta), path(countMatrix) ]
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'test', chromosome: 'chr22', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3 ]`
        - countMatrix:
            type: file
            description: RDS file containing the simulated count matrices
            pattern: "countMatrix_*.rds"
  - expectedLog2FC:
      description: |
        Channel containing the expected log2foldchange
        Structure: [ val(meta), path(expectedLog2FC) ]
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'test', chromosome: 'chr22', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3 ]`
        - expectedLog2FC:
            type: file
            description: RDS file containing the expected log2foldchange for each DE gene
            pattern: "expected_*.rds"
  - simreads:
      description: |
        Channel containing the simulated reads with a new meta containing also the DE genes
        Structure: [ val(newmeta), path(simreads) ]
      structure:
        - newmeta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'test', chromosome: 'chr22', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3, genes: 'A,B,C' ]`
        - simreads:
            type: file
            description: controls/cases simulated reads
            pattern: "*.fasta.gz"
  - versions:
      description: |
        Channel containing software versions file
      structure:
        - versions.yml:
            type: file
            description: file containing versions of the software used
authors:
  - "@LorenzoS96"
maintainers:
  - "@LorenzoS96"
