name: "subcapture"
description: Subset the capture BED by chromosome
keywords:
  - bed
  - capture
  - chromosome
tools:
  - bgzip:
      description: Block compression/decompression utility
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/bgzip.html
      licence: ["MIT"]
  - tabix:
      description: Index tab-delimited genome position files
      homepage: http://www.htslib.org/doc/tabix.html
      documentation: http://www.htslib.org/doc/tabix.html
      licence: ["MIT"]
      identifier: biotools:tabix
  - bedtools:
      description: A powerful toolset for genome arithmetic
      homepage: https://bedtools.readthedocs.io/
      documentation: https://bedtools.readthedocs.io/
      licence: ["MIT"]
      identifier: biotools:bedtools

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - target_chrom_size:
      type: file
      description: Chromosome sizes file
      pattern: "*.{txt,tsv}"
  - capture_bed:
      type: file
      description: Capture regions in BED format
      pattern: "*.{bed,bed.gz}"

output:
  - capture_bed_gz:
      - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.capture.bed.gz":
          type: file
          description: Compressed origin capture BED
          pattern: "*.capture.bed.gz"
  - capture_bed_index:
      - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.capture.bed.gz.tbi":
          type: file
          description: Index of compressed origin capture BED
          pattern: "*.capture.bed.gz.tbi"
  - target_bed:
      - meta:
          type: map
          description: Groovy Map containing sample information
      - "*_*_target.bed":
          type: file
          description: Capture BED subset by target chromosome
          pattern: "*_*_target.bed"
  - target_bed_pad50:
      - meta:
          type: map
          description: Groovy Map containing sample information
      - "*_*_target.pad50.bed":
          type: file
          description: Target capture BED padded by 50 positions
          pattern: "*_*_target.pad50.bed"
  - target_bed_pad500:
      - meta:
          type: map
          description: Groovy Map containing sample information
      - "*_*_target.pad500.bed":
          type: file
          description: Target capture BED padded by 500 positions
          pattern: "*_*_target.pad500.bed"
  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@msantorsola"
maintainers:
  - "@msantorsola"
