---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "aiscenarios"
description: This module uses Gemini Flash to generate clinical scenarios plausible with the simulated variant (for re sequencing datasets) or the differentially expressed genes (for RNAseq datasets).
keywords:
  - gemini
  - generation
  - scenarios
tools:
  - "aiscenarios":
      description: "This module uses Gemini Flash to generate clinical scenarios plausible with the simulated variant (for re sequencing datasets) or the differentially expressed genes (for RNAseq datasets)."
      homepage: "https://gemini.google.com/app"
      documentation: ""
      tool_dev_url: "https://gemini.google.com/app"
      doi: ""
      licence: ["MIT"]
      identifier:
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
  - variant:
      type: string
      description: Variant information for scenario generation
      pattern: "*.{vcf,vcf.gz}"
  - meta2:
      type: map
      description: |
        Groovy Map containing sample information for genes
        e.g. [ id:'sample2', single_end:false ]
  - genes:
      type: string
      description: Gene information for differential expression scenario generation

output:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
  - scenario:
      type: file
      description: Generated AI scenario
      pattern: "*_scenario.txt"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
      
authors:
  - "@lescai"
maintainers:
  - "@lescai"
