name: SUBSETFASTATX
description: Subsets a FASTA file based on a specified chromosome and GFF3 annotations
keywords:
  - fasta
  - subset
  - transcriptome
  - gff3
  - chromosome
tools:
  - bioconductor-rtracklayer:
      description: Importing GFF3 files
      homepage: https://bioconductor.org/packages/release/bioc/html/rtracklayer.html
      documentation: https://bioconductor.org/packages/release/bioc/vignettes/rtracklayer/inst/doc/rtracklayer.html
  - bioconductor-biostrings:
      description: Efficient manipulation of biological strings
      homepage: https://bioconductor.org/packages/release/bioc/html/Biostrings.html
      documentation: https://bioconductor.org/packages/release/bioc/vignettes/Biostrings/inst/doc/BiostringsQuickOverview.pdf
  - r-tidyverse:
      description: Collection of R packages for data science
      homepage: https://www.tidyverse.org/
      documentation: https://www.tidyverse.org/packages/
input:
  - meta:
      type: map
      description: Metadata map
  - txfasta:
      type: file
      description: Transcriptome FASTA file
      pattern: "*.{fa,fasta}"
  - gff3:
      type: file
      description: GFF3 annotation file
      pattern: "*.{gff3}"
output:
  - fasta:
      - meta:
          type: file
          description: Subset FASTA file containing transcripts from the specified chromosome
          pattern: "gencode_transcripts_noversion_dummy.fasta"
      - "gencode_transcripts_noversion_dummy.fasta":
          type: file
          description: Subset FASTA file containing transcripts from the specified chromosome
          pattern: "gencode_transcripts_noversion_dummy.fasta"
  - log:
      - meta:
          type: file
          description: Log file containing parsing and analysis information
          pattern: "subsetfastatx_parsing_log.txt"
      - "subsetfastatx_parsing_log.txt":
          type: file
          description: Log file containing parsing and analysis information
          pattern: "subsetfastatx_parsing_log.txt"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@carpanz"
  - "@LorenzoS96"
maintainers:
  - "@carpanz"
  - "@LorenzoS96"
