name: SUBSETFASTATX
description: subsets a FASTA file based on a simulated chromosome and GFF3 annotations
keywords:
  - fasta
  - subset
  - transcriptome
tools:
  - bioconductor-biostrings:
      description: Efficient manipulation of biological strings
      homepage: https://bioconductor.org/packages/release/bioc/html/Biostrings.html
      documentation: https://bioconductor.org/packages/release/bioc/vignettes/Biostrings/inst/doc/BiostringsQuickOverview.pdf
      tool_dev_url: "https://github.com/tidyverse/tidyverse"
      doi: "10.18129/B9.bioc.Biostrings"
      licence: ["Artistic-2.0"]
      identifier: "biotools:biostrings"
  - r-tidyverse:
      description: Collection of R packages for data science
      homepage: https://www.tidyverse.org/
      documentation: https://www.tidyverse.org/packages/
      tool_dev_url: "https://github.com/tidyverse/tidyverse"
      doi: "10.21105/joss.01686"
      licence: ["MIT"]
      identifier: "r-tidyverse"
input:
  - - txfasta:
      type: file
      description: transcriptome FASTA file
      pattern: "*.{fa,fasta}"
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', chromosome: 'chr22', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3 ]`
    - filtered_transcript_data:
        type: file
        description: RDS file containing transcript data from the simulated chromosome
        pattern: "filtered_transcript_data.rds"
output:
  - filtered_txfasta:
      - meta:
          type: file
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', chromosome: 'chr22', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3 ]`
      - "gencode_transcripts_novers_simchr.fasta":
          type: file
          description: subset FASTA file containing transcripts from the simulated chromosome
          pattern: "gencode_transcripts_novers_simchr.fasta"
  - subsetfastatx_parsing_log:
      - meta:
          type: file
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', chromosome: 'chr22', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3 ]`
      - "subsetfastatx_parsing_log.txt":
          type: file
          description: TXT log file containing parsing and analysis information
          pattern: "subsetfastatx_parsing_log.txt"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@carpanz"
  - "@LorenzoS96"
maintainers:
  - "@carpanz"
  - "@LorenzoS96"
