# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "fasta_wgsim_to_profile"
description: Generate sequencing profile from FASTA using WGSIM simulation and GATK variant calling pipeline
keywords:
  - simulation
  - wgsim
  - bwa
  - gatk
  - variant calling
  - profiling
components:
  - wgsim
  - bwa/mem
  - samtools/index
  - gatk4/markduplicates
  - gatk4/baserecalibrator
  - gatk4/applybqsr
  - gatk4/haplotypecaller
  - simuscop/seqtoprofile
input:
  - fasta:
      type: file
      description: |
        Reference FASTA file
        Structure: [ val(meta), path(fasta) ]
      pattern: "*.{fa,fasta}"
  - fai:
      type: file
      description: |
        FASTA index file
        Structure: [ val(meta), path(fai) ]
      pattern: "*.fai"
  - dict:
      type: file
      description: |
        FASTA dictionary file
        Structure: [ val(meta), path(dict) ]
      pattern: "*.dict"
  - bwa_index:
      type: directory
      description: |
        BWA index directory
        Structure: [ val(meta), path(bwa_index) ]
  - dbsnp:
      type: file
      description: |
        dbSNP VCF file
        Structure: [ path(dbsnp) ]
      pattern: "*.vcf.gz"
  - dbsnp_tbi:
      type: file
      description: |
        dbSNP VCF index file
        Structure: [ path(dbsnp_tbi) ]
      pattern: "*.vcf.gz.tbi"
  - mills:
      type: file
      description: |
        Mills indels VCF file
        Structure: [ path(mills) ]
      pattern: "*.vcf.gz"
  - mills_tbi:
      type: file
      description: |
        Mills indels VCF index file
        Structure: [ path(mills_tbi) ]
      pattern: "*.vcf.gz.tbi"
  - capture:
      type: file
      description: |
        Capture regions file
        Structure: [ path(capture) ]
output:
  - bam:
      type: file
      description: |
        Processed BAM files
        Structure: [ val(meta), path(bam) ]
      pattern: "*.bam"
  - vcf:
      type: file
      description: |
        Called variants VCF files
        Structure: [ val(meta), path(vcf) ]
      pattern: "*.vcf.gz"
  - profile:
      type: file
      description: |
        Generated sequencing profiles
        Structure: [ val(meta), path(profile) ]
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@lescai"
maintainers:
  - "@lescai"
