name: "enrichment"
description: performs enrichment analysis on DE genes
keywords:
  - enrichment
  - gene ontology
  - pathway analysis
tools:
  - tidyverse:
      description: "A collection of R packages designed for data science"
      homepage: "https://www.tidyverse.org/"
      documentation: "https://www.tidyverse.org/packages/"
      tool_dev_url: "https://github.com/tidyverse"
      doi: "10.21105/joss.01686"
      licence: ["MIT"]
      identifier: "r-tidyverse"
  - org.Hs.eg.db:
      description: "Genome wide annotation for Human"
      homepage: "https://bioconductor.org/packages/release/data/annotation/html/org.Hs.eg.db.html"
      documentation: "https://bioconductor.org/packages/release/data/annotation/manuals/org.Hs.eg.db/man/org.Hs.eg.db.pdf"
      tool_dev_url: "https://github.com/Bioconductor/org.Hs.eg.db"
      doi: "10.18129/B9.bioc.org.Hs.eg.db"
      licence: ["Artistic-2.0"]
      identifier: "bioconductor-org.hs.eg.db"
  - clusterProfiler:
      description: "Statistical analysis and visualization of functional profiles for genes and gene clusters"
      homepage: "https://bioconductor.org/packages/release/bioc/html/clusterProfiler.html"
      documentation: "https://yulab-smu.top/biomedical-knowledge-mining-book/"
      tool_dev_url: "https://github.com/YuLab-SMU/clusterProfiler"
      doi: "10.1089/omi.2011.0118"
      licence: ["Artistic-2.0"]
      identifier: "biotools:clusterprofiler"
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id: 'simulation_id', chromosome: 'chr_number', genes: 'A,B,C', reps: 3, groups: 2 ]`
    - resdata:
        type: file
        description: RDS file containing the DESeq2 results for the genes from the selected chromosome
        pattern: "resdata.rds"
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id: 'simulation_id', chromosome: 'chr_number', genes: 'A,B,C', reps: 3, groups: 2 ]`
    - tx2gene:
        type: file
        description: TSV mapping transcripts to genes
        pattern: "tx2gene.tsv"
output:
  - enrichment_results:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id: 'simulation_id', chromosome: 'chr_number', genes: 'A,B,C', reps: 3, groups: 2 ]`
      - "enrichment_results.rds":
          type: file
          description: RDS file containing enrichment results
          pattern: "enrichment_results.rds"
      - "dotplot_BP.png":
          type: file
          description: dotplot of enriched biological processes
          pattern: "dotplot_BP.png"
      - "dotplot_MF.png":
          type: file
          description: dotplot of enriched molecolar functions
          pattern: "dotplot_MF.png"
      - "dotplot_CC.png":
          type: file
          description: dotplot of enriched cellular components
          pattern: "dotplot_CC.png"
      - "cnetplot_BP.png":
          type: file
          description: cnetplot of enriched biological processes
          pattern: "cnetplot_BP.png"
      - "cnetplot_MF.png":
          type: file
          description: cnetplot of enriched molecular functions
          pattern: "cnetplot_MF.png"
      - "cnetplot_CC.png":
          type: file
          description: cnetplot of enriched cellular components
          pattern: "cnetplot_CC.png"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@LorenzoS96"
maintainers:
  - "@LorenzoS96"
