---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "subset_references_to_targets"
description: Subset Human genome fasta, capture BED, GATK bundle and ClinVar VCFs by target chromosome
keywords:
  - subset
  - reference
  - capture
  - genomics
  - variants
components:
  - samtools/faidx
  - gatk4/selectvariants
  - gatk4/createsequencedictionary
  - subsetcapture
  - subvar
  - bwa/index
input:
  - ch_meta:
      type: value
      description: |
        a Groovy map containing sample information i.e. [ id:'test', chromosome:'chr22', type:'dnaseq' ]
        Structure: [ val(meta) ]
  - ch_fasta:
      type: file
      description: |
        The input channel containing reference fasta file
        Structure: [ path(fasta) ]
      pattern: "*.{fa,fasta}"
  - ch_get_sizes:
      type: boolean
      description: |
        Boolean value to determine if sizes should be calculated
        Structure: [ get_sizes ]
  - capture_bed:
      type: boolean
      description: |
        Capture bed file
        Structure: [ path(capture_bed) ]
      pattern: "*.bed"
  - ch_gnomad:
      description: |
        Channel with the gnomAD VCF file and index
        Structure: [ path(vcf), path(vcf_idx) ]
      structure:
        - gnomad_vcf:
            type: file
            description: |
              VCF(.gz) file
            pattern: "*.{vcf,vcf.gz}"
        - gnomad_tbi:
            type: file
            description: VCF file index
            pattern: "*.{idx,tbi}"
  - ch_mills:
      description: |
        Channel with the Mills VCF file and index
        Structure: [ path(vcf), path(vcf_idx) ]
      structure:
        - mills_vcf:
            type: file
            description: |
              VCF(.gz) file
            pattern: "*.{vcf,vcf.gz}"
        - mills_tbi:
            type: file
            description: VCF file index
            pattern: "*.{idx,tbi}"
  - ch_1000g:
      description: |
        Channel with the 1000G VCF file and index
        Structure: [ path(vcf), path(vcf_idx) ]
      structure:
        - 1000g_vcf:
            type: file
            description: |
              VCF(.gz) file
            pattern: "*.{vcf,vcf.gz}"
        - 1000g_tbi:
            type: file
            description: VCF file index
            pattern: "*.{idx,tbi}"
  - ch_dbsnp:
      description: |
        Channel with the dbsnp VCF file and index
        Structure: [ path(vcf), path(vcf_idx) ]
      structure:
        - dbsnp_vcf:
            type: file
            description: |
              VCF(.gz) file
            pattern: "*.{vcf,vcf.gz}"
        - dbsnp_tbi:
            type: file
            description: VCF file index
            pattern: "*.{idx,tbi}"
  - ch_clinvar_vcf:
      type: file
      description: |
        ClinVar VCF file
        Structure: [ path(clinvar_vcf) ]
      pattern: "*.{vcf,vcf.gz}"
output:
  - target_fa:
      description: |
        Channel containing salmon quantification files  i.e. [ id:'test', chromosome:'chr22', type:'dnaseq' ]
        Structure: [ val(meta), path(fasta) ]
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'test', chromosome:'chr22', type:'dnaseq' ]`
        - fasta:
            type: file
            description: Subset fasta file
            pattern: "*.{fa,fasta}"
  - target_fai:
      description: |
        Channel containing FASTA index files
        Structure: [ val(meta), path(fai) ]
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'test', chromosome:'chr22', type:'dnaseq' ]`
        - fai:
            type: file
            description: FASTA index file
            pattern: "*.fai"
  - target_sizes:
      description: |
        Channel containing chromosome sizes files
        Structure: [ val(meta), path(sizes) ]
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'test', chromosome:'chr22', type:'dnaseq' ]`
        - sizes:
            type: file
            description: Chromosome sizes file
            pattern: "*.sizes"
  - target_bwa_index:
      description: |
        Channel containing BWA index files
        Structure: [ val(meta), path(bwa_index) ]
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'test', chromosome:'chr22', type:'dnaseq' ]`
        - bwa_index:
            type: directory
            description: BWA index directory
  - capture_bed_gz:
      description: |
        Channel containing compressed capture BED files
        Structure: [ path(capture_bed_gz) ]
      structure:
        - capture_bed_gz:
            type: file
            description: Compressed capture BED file
            pattern: "*.bed.gz"
  - capture_bed_index:
      description: |
        Channel containing capture BED index files
        Structure: [ path(capture_bed_index) ]
      structure:
        - capture_bed_index:
            type: file
            description: Capture BED index file
            pattern: "*.bed.gz.tbi"
  - target_bed:
      description: |
        Channel containing target BED files
        Structure: [ path(target_bed) ]
      structure:
        - target_bed:
            type: file
            description: Target regions BED file
            pattern: "*.bed"
  - target_bed_pad50:
      description: |
        Channel containing target BED files with 50bp padding
        Structure: [ path(target_bed_pad50) ]
      structure:
        - target_bed_pad50:
            type: file
            description: Target regions BED file with 50bp padding
            pattern: "*.bed"
  - target_bed_pad500:
      description: |
        Channel containing target BED files with 500bp padding
        Structure: [ path(target_bed_pad500) ]
      structure:
        - target_bed_pad500:
            type: file
            description: Target regions BED file with 500bp padding
            pattern: "*.bed"
  - target_gnomad_vcf:
      description: |
        Channel containing subset gnomAD VCF files
        Structure: [ path(vcf) ]
      structure:
        - vcf:
            type: file
            description: Subset gnomAD VCF file
            pattern: "*.{vcf,vcf.gz}"
  - target_gnomad_tbi:
      description: |
        Channel containing subset gnomAD VCF index files
        Structure: [ path(tbi) ]
      structure:
        - tbi:
            type: file
            description: Subset gnomAD VCF index file
            pattern: "*.{idx,tbi}"
  - target_mills_vcf:
      description: |
        Channel containing subset Mills VCF files
        Structure: [ path(vcf) ]
      structure:
        - vcf:
            type: file
            description: Subset Mills indels VCF file
            pattern: "*.{vcf,vcf.gz}"
  - target_mills_tbi:
      description: |
        Channel containing subset Mills VCF index files
        Structure: [ path(tbi) ]
      structure:
        - tbi:
            type: file
            description: Subset Mills indels VCF index file
            pattern: "*.{idx,tbi}"
  - target_1000g_vcf:
      description: |
        Channel containing subset 1000G VCF files
        Structure: [ path(vcf) ]
      structure:
        - vcf:
            type: file
            description: Subset 1000 Genomes VCF file
            pattern: "*.{vcf,vcf.gz}"
  - target_1000g_tbi:
      description: |
        Channel containing subset 1000G VCF index files
        Structure: [ path(tbi) ]
      structure:
        - tbi:
            type: file
            description: Subset 1000 Genomes VCF index file
            pattern: "*.{idx,tbi}"
  - target_dbsnp_vcf:
      description: |
        Channel containing subset dbSNP VCF files
        Structure: [ path(vcf) ]
      structure:
        - vcf:
            type: file
            description: Subset dbSNP VCF file
            pattern: "*.{vcf,vcf.gz}"
  - target_dbsnp_tbi:
      description: |
        Channel containing subset dbSNP VCF index files
        Structure: [ path(tbi) ]
      structure:
        - tbi:
            type: file
            description: Subset dbSNP VCF index file
            pattern: "*.{idx,tbi}"
  - clinvar_benign_vcf:
      description: |
        Channel containing ClinVar benign variants VCF files
        Structure: [ val(meta), path(benign_vcf) ]
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'test', chromosome:'chr22', type:'dnaseq' ]`
        - benign_vcf:
            type: file
            description: ClinVar benign variants VCF file
            pattern: "*.{vcf,vcf.gz}"
  - clinvar_pathogenic_vcf:
      description: |
        Channel containing ClinVar pathogenic variants VCF files
        Structure: [ val(meta), path(pathogenic_vcf) ]
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'test', chromosome:'chr22', type:'dnaseq' ]`
        - pathogenic_vcf:
            type: file
            description: ClinVar pathogenic variants VCF file
            pattern: "*.{vcf,vcf.gz}"
  - clinvar_selected_vcf:
      description: |
        Channel containing ClinVar selected variants VCF files
        Structure: [ val(meta), path(selected_vcf) ]
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'test', chromosome:'chr22', type:'dnaseq' ]`
        - selected_vcf:
            type: file
            description: ClinVar selected variants VCF file
            pattern: "*.{vcf,vcf.gz}"
  - target_dict:
      description: |
        Channel containing sequence dictionary files
        Structure: [ val(meta), path(dict) ]
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'test', chromosome:'chr22', type:'dnaseq' ]`
        - dict:
            type: file
            description: Sequence dictionary file
            pattern: "*.dict"
  - versions:
      description: |
        Channel containing software versions
        Structure: [ versions.yml ]
      structure:
        - versions.yml:
            type: file
            description: File containing software versions
            pattern: "versions.yml"
  - dna_bundle:
      description: |
        Channel containing all reference files bundled together
        Structure: [ val(meta), path [all references bundle] ]
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. `[ id:'test', chromosome:'chr22', type:'dnaseq' ]`
        - bundle:
            type: array
            description: Array containing all reference files (FASTA, FAI, BED files, VCF files, indices, dictionary, BWA index)
authors:
  - "@msantorsola"
maintainers:
  - "@msantorsola"
