# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "subset_references_to_targets"
description: Subset Human genome fasta, capture BED, GATK bundle and ClinVar VCFs by target chromosome
keywords:
  - subset
  - reference
  - capture
  - genomics
  - variants
components:
  - samtools/faidx
  - gatk4/selectvariants
  - local/subsetcapture
  - local/subvar

input:
  - - meta:
        type: map
        description: [id:'test', chromosome:'chr22', type: "dnaseq"]
    - fasta:
        type: file
        description: Reference fasta file
        pattern: "*.{fa,fasta}"
  - - meta:
        type: map
        description: Metadata map
    - fai:
        type: file
        description: Fasta index file
        pattern: "*.fai"
  - - get_sizes:
        type: boolean
        description: Boolean value to determine if sizes should be calculated
  - - capture_bed:
        type: file
        description: Capture bed file
        pattern: "*.bed"
  - - meta:
        type: map
        description: Metadata map
    - chromosome:
        type: value
        description: Chromosome information
  - - meta:
        type: map
        description: Metadata map
    - gnomad_vcf:
        type: file
        description: gnomAD VCF file
        pattern: "*.vcf{.gz,}"
    - gnomad_tbi:
        type: file
        description: gnomAD VCF index file
        pattern: "*.{tbi,idx}"
  - - meta:
        type: map
        description: Metadata map
    - mills_vcf:
        type: file
        description: Mills VCF file
        pattern: "*.vcf{.gz,}"
    - mills_tbi:
        type: file
        description: Mills VCF index file
        pattern: "*.{tbi,idx}"
  - - meta:
        type: map
        description: Metadata map
    - 1000g_vcf:
        type: file
        description: 1000G VCF file
        pattern: "*.vcf{.gz,}"
    - 1000g_tbi:
        type: file
        description: 1000G VCF index file
        pattern: "*.{tbi,idx}"
  - - meta:
        type: map
        description: Metadata map
    - dbsnp_vcf:
        type: file
        description: dbSNP VCF file
        pattern: "*.vcf{.gz,}"
    - dbsnp_tbi:
        type: file
        description: dbSNP VCF index file
        pattern: "*.{tbi,idx}"
  - - meta:
        type: map
        description: Metadata map
    - clinvar_vcf:
        type: file
        description: ClinVar VCF file
        pattern: "*.vcf{.gz,}"
output:
  - target_fa:
      - meta:
          type: map
          description: Metadata map
      - fa:
          type: file
          description: Subset fasta file
          pattern: "*.{fa,fasta}"
  - target_fai:
      - meta:
          type: map
          description: Metadata map
      - fai:
          type: file
          description: Subset fasta index file
          pattern: "*.fai"
  - target_sizes:
      - meta:
          type: map
          description: Metadata map
      - sizes:
          type: file
          description: Subset sizes file
          pattern: "*.sizes"
  - capture_bed_gz:
      - meta:
          type: map
          description: Metadata map
      - bed_gz:
          type: file
          description: Gzipped capture bed file
          pattern: "*.bed.gz"
  - capture_bed_index:
      - meta:
          type: map
          description: Metadata map
      - bed_index:
          type: file
          description: Capture bed index file
          pattern: "*.bed.gz.tbi"
  - target_bed:
      - meta:
          type: map
          description: Metadata map
      - bed:
          type: file
          description: Target bed file
          pattern: "*.bed"
  - target_bed_pad50:
      - meta:
          type: map
          description: Metadata map
      - bed_pad50:
          type: file
          description: Target bed file with 50bp padding
          pattern: "*_pad50.bed"
  - target_bed_pad500:
      - meta:
          type: map
          description: Metadata map
      - bed_pad500:
          type: file
          description: Target bed file with 500bp padding
          pattern: "*_pad500.bed"
  - target_gnomad_vcf:
      - meta:
          type: map
          description: Metadata map
      - vcf:
          type: file
          description: Subset gnomAD VCF file
          pattern: "*.vcf{.gz,}"
  - target_gnomad_tbi:
      - meta:
          type: map
          description: Metadata map
      - tbi:
          type: file
          description: Subset gnomAD VCF index file
          pattern: "*.{tbi,idx}"
  - target_mills_vcf:
      - meta:
          type: map
          description: Metadata map
      - vcf:
          type: file
          description: Subset Mills VCF file
          pattern: "*.vcf{.gz,}"
  - target_mills_tbi:
      - meta:
          type: map
          description: Metadata map
      - tbi:
          type: file
          description: Subset Mills VCF index file
          pattern: "*.{tbi,idx}"
  - target_1000g_vcf:
      - meta:
          type: map
          description: Metadata map
      - vcf:
          type: file
          description: Subset 1000G VCF file
          pattern: "*.vcf{.gz,}"
  - target_1000g_tbi:
      - meta:
          type: map
          description: Metadata map
      - tbi:
          type: file
          description: Subset 1000G VCF index file
          pattern: "*.{tbi,idx}"
  - target_dbsnp_vcf:
      - meta:
          type: map
          description: Metadata map
      - vcf:
          type: file
          description: Subset dbSNP VCF file
          pattern: "*.vcf{.gz,}"
  - target_dbsnp_tbi:
      - meta:
          type: map
          description: Metadata map
      - tbi:
          type: file
          description: Subset dbSNP VCF index file
          pattern: "*.{tbi,idx}"
  - clinvar_benign_vcf:
      - meta:
          type: map
          description: Metadata map
      - vcf:
          type: file
          description: Subset ClinVar benign VCF file
          pattern: "*_benign.vcf{.gz,}"
  - clinvar_pathogenic_vcf:
      - meta:
          type: map
          description: Metadata map
      - vcf:
          type: file
          description: Subset ClinVar pathogenic VCF file
          pattern: "*_pathogenic.vcf{.gz,}"
  - clinvar_selected_vcf:
      - meta:
          type: map
          description: Metadata map
      - vcf:
          type: file
          description: Subset ClinVar selected VCF file
          pattern: "*_selected.vcf{.gz,}"
  - versions:
      - versions:
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@msantorsola"
maintainers:
  - "@msantorsola"
