name: "countmatrices"
description: Count matrices generation for simulation of RNA-seq data
keywords:
  - count
  - matrix
  - simulation
  - rna-seq
tools:
  - tidyverse:
      description: "A collection of R packages designed for data science"
      homepage: "https://www.tidyverse.org/"
      documentation: "https://www.tidyverse.org/packages/"
      tool_dev_url: "https://github.com/tidyverse"
      doi: "10.21105/joss.01686"
      licence: ["MIT"]
      identifier: "r-tidyverse"
  - bioconductor-biostrings:
      description: "Efficient manipulation of biological strings in R, including DNA, RNA, and amino acid sequences"
      homepage: "https://bioconductor.org/packages/release/bioc/html/Biostrings.html"
      documentation: "https://bioconductor.org/packages/release/bioc/vignettes/Biostrings/inst/doc/Biostrings2Classes.pdf"
      tool_dev_url: "https://github.com/Bioconductor/Biostrings"
      doi: "10.18129/B9.bioc.Biostrings"
      licence: ["Artistic-2.0"]
      identifier: "bioconductor-biostrings"
input:
  - meta:
      type: map
      description: Metadata map
  - txfasta:
      type: file
      description: Transcriptome FASTA file
      pattern: "*.{fa,fasta}"
  - gff3:
      type: file
      description: GFF3 annotation file
      pattern: "*.gff3"
  - geneList:
      type: file
      description: Gene list file that should give an enrichment
      pattern: "*.rds"
output:
  - simcountMatrix:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id: 'simulation_id', chromosome: 'chr_number', genes: 'A, B, C', reps: 3, groups: 2 ]`
      - "countmatrix_*.rds":
          type: file
          description: RDS file containing the count matrices
          pattern: "countmatrix_*.rds"
  - simAnnords:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id: 'simulation_id', chromosome: 'chr_number', genes: 'A, B, C', reps: 3, groups: 2 ]`
      - "expected_*.rds":
          type: file
          description: Gene info and expected log2 fold change in RDS format
          pattern: "expected_*.rds"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "LorenzoS96"
  - "carpanz"
maintainers:
  - "LorenzoS96"
  - "carpanz"
