# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "fastq_variant_to_validation"
description: Perform variant calling and validation on simulated FASTQ reads
keywords:
  - variant calling
  - validation
  - GATK
  - BWA
  - SAMtools
components:
  - samtools/index
  - samtools/sort
  - bwa/mem
  - gatk4/markduplicates
  - gatk4/baserecalibrator
  - gatk4/applybqsr
  - gatk4/haplotypecaller
  - gatk4/genomicsdbimport
  - gatk4/genotypegvcfs
  - dnavalidation
input:
  - reads:
      type: file
      description: |
        Channel containing input FASTQ files
        Structure: [ val(meta), [ reads ] ]
      pattern: "*.fastq.gz"
  - fasta:
      type: file
      description: |
        Channel containing reference genome FASTA file
        Structure: [ val(meta), [ fasta ] ]
      pattern: "*.{fa,fasta}"
  - fai:
      type: file
      description: |
        Channel containing FASTA index file
        Structure: [ val(meta), [ fai ] ]
      pattern: "*.fai"
  - dict:
      type: file
      description: |
        Channel containing sequence dictionary file
        Structure: [ val(meta), [ dict ] ]
      pattern: "*.dict"
  - bwa_index:
      type: file
      description: |
        Channel containing BWA index files
        Structure: [ val(meta), [ bwa_index ] ]
      pattern: "*.{amb,ann,bwt,pac,sa}"
  - dbsnp:
      type: file
      description: |
        Channel containing dbSNP VCF file
        Structure: [ [ dbsnp ] ]
      pattern: "*.vcf.gz"
  - dbsnp_tbi:
      type: file
      description: |
        Channel containing dbSNP VCF index file
        Structure: [ [ dbsnp_tbi ] ]
      pattern: "*.vcf.gz.tbi"
  - mills:
      type: file
      description: |
        Channel containing Mills and 1000G gold standard indels VCF file
        Structure: [ [ mills ] ]
      pattern: "*.vcf.gz"
  - mills_tbi:
      type: file
      description: |
        Channel containing Mills and 1000G gold standard indels VCF index file
        Structure: [ [ mills_tbi ] ]
      pattern: "*.vcf.gz.tbi"
  - capture:
      type: file
      description: |
        Channel containing capture regions BED file
        Structure: [ [ capture ] ]
      pattern: "*.bed"
output:
  - simulation:
      type: file
      description: |
        Channel containing DNA validation results
        Structure: [ val(meta), path(validated_results_folder/*) ]
      pattern: "*"
  - scenario:
      type: value
      description: |
        Channel containing scenario information
        Structure: [ val(meta), val(variant) ]
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ versions.yml ]
      pattern: "versions.yml"
authors:
  - "@lescai"
maintainers:
  - "@lescai"
