---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "rnaseqvalidation"
description: validates RNA-seq enrichment results
keywords:
  - rnaseq
  - validation
  - enrichment
tools:
  - DOSE:
      description: "R/Bioconductor package for Disease Ontology Semantic and Enrichment analysis"
      homepage: "https://bioconductor.org/packages/release/bioc/html/DOSE.html"
      documentation: "https://yulab-smu.top/biomedical-knowledge-mining-book/"
      tool_dev_url: "https://github.com/YuLab-SMU/DOSE"
      doi: "10.1093/bioinformatics/btu684"
      licence: ["Artistic-2.0"]
      identifier: biotools:DOSE
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id: 'simulation_id', chromosome: 'chr_number', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3, genes: 'A,B,C' ]`
    - enrichment_results:
        type: file
        description: RDS file containing enrichment results
        pattern: "enrichment_results.rds"
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id: 'simulation_id', chromosome: 'chr_number', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3, genes: 'A,B,C' ]`
    - reads:
        type: file
        description: simulated reads in FASTA format
        pattern: "*.fasta.gz"
  - - meta3:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id: 'simulation_id', chromosome: 'chr_number', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3, genes: 'A,B,C' ]`
    - de_genes:
        type: file
        description: file containing differentially expressed genes
        pattern: "de_genes.txt"
output:
  - valid_reads:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id: 'simulation_id', chromosome: 'chr_number', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3, genes: 'A,B,C' ]`
      - "*.fasta.gz":
          type: file
          description: validated reads in FASTA format
          pattern: "*.fasta.gz"
  - valid_de_genes:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id: 'simulation_id', chromosome: 'chr_number', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3, genes: 'A,B,C' ]`
      - "validated_de_genes.txt":
          type: file
          description: file containing validated DE genes
          pattern: "validated_de_genes.txt"
  - validation_result:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id: 'simulation_id', chromosome: 'chr_number', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3, genes: 'A,B,C' ]`
      - "validation_result.txt":
          type: file
          description: file containing the result of the validation process, e.g (SIMULATION GOOD or SIMULATION NOT GOOD)
          pattern: "validation_result.txt"
  - versions:
      - versions.yml:
          type: file
          description: file containing software versions
          pattern: "versions.yml"
authors:
  - "@LorenzoS96"
maintainers:
  - "@LorenzoS96"
