---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "rnaseqvalidation"
description: validates RNA-seq enrichment results
keywords:
  - rnaseq
  - validation
  - enrichment
tools:
  - DOSE:
      description: "Bioconductor package for Disease Ontology Semantic and Enrichment analysis"
      homepage: "https://bioconductor.org/packages/release/bioc/html/DOSE.html"
      documentation: "https://yulab-smu.top/biomedical-knowledge-mining-book/"
      tool_dev_url: "https://github.com/YuLab-SMU/DOSE"
      doi: "10.1093/bioinformatics/btu684"
      licence: ["Artistic-2.0"]
      identifier: biotools:DOSE
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id: 'simulation_id', chromosome: 'chr_number', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3, genes: 'A,B,C' ]`
    - reads:
        type: file
        description: simulated reads in FASTA format
        pattern: "*.fasta.gz"
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id: 'simulation_id', chromosome: 'chr_number', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3, genes: 'A,B,C' ]`
    - deseq2_results_tsv:
        type: file
        description: TSV containing the DESeq2 results
        pattern: "deseq2_results.tsv"
    - deseq2_tx2gene.txt:
        type: file
        description: TSV containing the association between genes_id and transcripts_id
        pattern: "deseq2_tx2gene.tsv"
    - deseq2_de_genes_txt:
        type: file
        description: file containing the DE genes (padj < 0.05)
        pattern: "deseq2_de_genes.txt"
    - deseq2_pdf:
        type: file
        description: MA plot, dispersion plot, count plot, heatmap and pca plot produced by DESeq2
        pattern: "*.pdf"
  - - meta3:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id: 'simulation_id', chromosome: 'chr_number', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3, genes: 'A,B,C' ]`
    - enrichment_results:
        type: file
        description: RDS file containing enrichment results
        pattern: "enrichment_results.rds"
    - enrichment_png:
        type: file
        description: dotplots and cnetplots of enriched BP, MF and CC
        pattern: "*.png"
output:
  - rnaseq_validated_results:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id: 'simulation_id', chromosome: 'chr_number', coverage: 30, reps: 3, groups: 2, simthreshold: 0.3, genes: 'A,B,C' ]`
      - "*.fasta.gz":
          type: file
          description: optional, validated reads in FASTA format
          pattern: "*.fasta.gz"
      - "deseq2_results.tsv":
          type: file
          description: optional, TSV containing the DESeq2 results
          pattern: "deseq2_results.tsv"
      - "deseq2_tx2gene.tsv":
          type: file
          description: optional, TSV containing the association between genes_id and transcripts_id
          pattern: "deseq2_results.tsv"
      - "deseq2_de_genes.txt":
          type: file
          description: optional, file containing the DE genes (padj < 0.05)
          pattern: "deseq2_de_genes.txt"
      - "deseq2_ma_plot.pdf":
          type: file
          description: optional, MA plot generated by DESeq2
          pattern: "deseq2_ma_plot.pdf"
      - "deseq2_dispersion_plot.pdf":
          type: file
          description: optional, dispersion plot generated by DESeq2
          pattern: "deseq2_dispersion_plot.pdf"
      - "deseq2_count_plot.pdf":
          type: file
          description: optional, plot of normalised counts
          pattern: "deseq2_count_plot.pdf"
      - "deseq2_heatmap_plot.pdf":
          type: file
          description: optional, heatmap of top 20 expressed genes
          pattern: "deseq2_heatmap_plot.pdf"
      - "deseq2_pca_plot.pdf":
          type: file
          description: optional, PCA plot
          pattern: "deseq2_pca_plot.pdf"
      - "enrichment_results.rds":
          type: file
          description: optional, RDS file containing enrichment results
          pattern: "enrichment_results.rds"
      - "dotplot_BP.png":
          type: file
          description: optional, dotplot of enriched biological processes
          pattern: "dotplot_BP.png"
      - "dotplot_MF.png":
          type: file
          description: optional, dotplot of enriched molecolar functions
          pattern: "dotplot_MF.png"
      - "dotplot_CC.png":
          type: file
          description: optional, dotplot of enriched cellular components
          pattern: "dotplot_CC.png"
      - "cnetplot_BP.png":
          type: file
          description: optional, cnetplot of enriched biological processes
          pattern: "cnetplot_BP.png"
      - "cnetplot_MF.png":
          type: file
          description: optional, cnetplot of enriched molecular functions
          pattern: "cnetplot_MF.png"
      - "cnetplot_CC.png":
          type: file
          description: optional, cnetplot of enriched cellular components
          pattern: "cnetplot_CC.png"
      - "validation_result.txt":
          type: file
          description: optional, TXT file containing the results of the validation process (SIMULATION GOOD or SIMULATION NOT GOOD)
          pattern: "validation_result.txt"
  - versions:
      - versions.yml:
          type: file
          description: file containing software versions
          pattern: "versions.yml"
authors:
  - "@LorenzoS96"
maintainers:
  - "@LorenzoS96"
